### ISSUE TITLE
error : ng build -w

### ISSUE THREAD

**Issue by kamalkech** [DavideViolante/Angular2-Full-Stack#16]
Node : v6.4.0
Npm : 3.10.7

I get erros bellow when run try to run "ng build -w" : 

Looks like you have a different program called watchman, falling back to NodeWatcher.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Path must be a string. Received null
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1148:7)
    at Class.exports.default.Task.extend.run (/Users/admin/Documents/Sites/Angular2-Full-Stack/node_modules/angular-cli/tasks/build-webpack-watch.js:14:26)
    at Class.Command.extend.run (/Users/admin/Documents/Sites/Angular2-Full-Stack/node_modules/angular-cli/commands/build.js:50:26)
    at Class.<anonymous> (/Users/admin/Documents/Sites/Angular2-Full-Stack/node_modules/angular-cli/lib/models/command.js:152:17)
    at tryCatch (/Users/admin/Documents/Sites/Angular2-Full-Stack/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/admin/Documents/Sites/Angular2-Full-Stack/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Users/jeanpeyroux/Documents/Sites/Angular2-Full-Stack/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Users/jeanpeyroux/Documents/Sites/Angular2-Full-Stack/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by DavideViolante** [comment]
This should be fixed with the latest update of the project. Please clone again and let me know.
