### ISSUE TITLE
I'm getting an error on npm start

### ISSUE THREAD

**Issue by marioteik** [DavideViolante/Angular2-Full-Stack#27]
Good evening!

For me the npm start is throwing some error and it's not running Angular Cli build:

[0] 2017-02-25T17:33:53.333-0300 I CONTROL  [initandlisten] MongoDB starting : pid=12712 port=27017 dbpath=C:\data\db\ 64-bit host=DESKTOP-T4Q8DTC
[0] 2017-02-25T17:33:53.335-0300 I CONTROL  [initandlisten] targetMinOS: Windows Vista/Windows Server 2008
[0] 2017-02-25T17:33:53.335-0300 I CONTROL  [initandlisten] db version v3.2.4
[0] 2017-02-25T17:33:53.335-0300 I CONTROL  [initandlisten] git version: e2ee9ffcf9f5a94fad76802e28cc978718bb7a30
[0] 2017-02-25T17:33:53.335-0300 I CONTROL  [initandlisten] allocator: tcmalloc
[0] 2017-02-25T17:33:53.335-0300 I CONTROL  [initandlisten] modules: none
[0] 2017-02-25T17:33:53.335-0300 I CONTROL  [initandlisten] build environment:
[0] 2017-02-25T17:33:53.335-0300 I CONTROL  [initandlisten]     distarch: x86_64
[0] 2017-02-25T17:33:53.335-0300 I CONTROL  [initandlisten]     target_arch: x86_64
[0] 2017-02-25T17:33:53.335-0300 I CONTROL  [initandlisten] options: {}
[0] 2017-02-25T17:33:53.337-0300 I -        [initandlisten] Detected data files in C:\data\db\ created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
[0] 2017-02-25T17:33:53.339-0300 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=4G,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(
close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
[1] C:\Users\mario\Desktop\mms3\node_modules\@angular\cli\models\config\config.js:15
[1]     constructor(_configPath, schema, configJson, fallbacks = []) {
[1]                                                            ^
[1]
[1] SyntaxError: Unexpected token =
[1]     at exports.runInThisContext (vm.js:53:16)
[1]     at Module._compile (module.js:387:25)
[1]     at Object.Module._extensions..js (module.js:422:10)
[1]     at Module.load (module.js:357:32)
[1]     at Function.Module._load (module.js:314:12)
[1]     at Module.require (module.js:367:17)
[1]     at require (internal/module.js:16:19)
[1]     at Object.<anonymous> (C:\Users\mario\Desktop\mms3\node_modules\@angular\cli\models\config.js:2:18)
[1]     at Module._compile (module.js:413:34)
[1]     at Object.Module._extensions..js (module.js:422:10)
[1] ng build -w exited with code 1
[0] 2017-02-25T17:33:54.907-0300 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker
[0] 2017-02-25T17:33:54.907-0300 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory 'C:/data/db/diagnostic.data'
[0] 2017-02-25T17:33:54.911-0300 I NETWORK  [initandlisten] waiting for connections on port 27017
[2] [nodemon] 1.11.0
[2] [nodemon] to restart at any time, enter `rs`
[2] [nodemon] watching: *.*
[2] [nodemon] starting `node src/server/app.js`
[0] 2017-02-25T17:33:57.273-0300 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:53851 #1 (1 connection now open)
[2] Connected to MongoDB
[2] Angular 2 Full Stack listening on port 3000

**Comment by DavideViolante** [comment]
Try updating angular-cli to rc0 and re-clone my project.

**Comment by marioteik** [comment]
Thank you. It worked.
